export const ADD_NUMBER = "ADD_NUMBER";
export const SUB_NUMBER = "SUB_NUMBER";

export const CHANGE_BANNER = "CHANGE_BANNER";
export const CHANGE_RECOMMEND = "CHANGE_RECOMMEND";

export const FETCH_ABOUT_DATA = "FETCH_ABOUT_DATA";
